import "./globals.css";
import type { Metadata } from "next";
import { Comfortaa, Montserrat, Rubik } from "next/font/google";
import Header from "@/components/Header/Header";
import NavigationContextProvider from "@/contexts/NavigationContext/NavigationContextProvider";
import Providers from "@/utils/store/provider";
import Footer from "@/components/Footer/Footer";
import { SkeletonTheme } from "react-loading-skeleton";
import * as firebase from "../utils/firebase/firebase";
import AuthContextProvider from "@/contexts/AuthContext/AuthContextProvider";
import ModalSignUp from "@/components/ModalSignUp/ModalSignUp";

const rubik = Rubik({ subsets: ["cyrillic"] });
const montserrat = Montserrat({subsets:['cyrillic']})
const comfarta = Comfortaa({subsets:['cyrillic']})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={[comfarta.className].join(" ")}>
        <Providers>
          <NavigationContextProvider>
            <AuthContextProvider>
              <Header />
              <main id="main" className="flex-1">
                {children}
              </main>
              <Footer />
              <ModalSignUp />
            </AuthContextProvider>
          </NavigationContextProvider>
        </Providers>
      </body>
    </html>
  );
}
